name: Build
on:
  push:
  pull_request:
jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Install dependencies"
        run: sudo apt-get install build-essential cmake qt5-default libprotobuf-dev protobuf-compiler libgrpc++-dev libgrpc-dev protobuf-compiler-grpc 
      - name: "Build"
        run: mkdir build && cd build && qmake .. && make -j8
